name: Generate CycloneDX SBOM

on:
  push:
    branches: [ master ] 
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18' #npm versie die de juice shop gebruikt

      - name: Install dependencies
        run: npm install # Juice Shop gebruikt npm

      - name: Generate CycloneDX SBOM
        with:
          output-format: 'json'
          output-file: 'sbom.json' # Naam van het SBOM bestand

      - name: Upload SBOM artifact
        uses: actions/upload-artifact@v3
        with:
          name: SBOM
          path: sbom.json
