name: SBOM Generator

on:
  push:
    branches: [ master ] # Pas aan naar 'main' of je default branch indien nodig
  pull_request:
    branches: [ master ] # Pas aan naar 'main' of je default branch indien nodig
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Generate SBOM
        uses: microsoft/sbom-tool@v1
        with:
          path: .
          name: juice-shop
          version: 1.0.0
          format: cyclonedx
          output-file: sbom.json

      - name: Upload SBOM artifact
        uses: actions/upload-artifact@v4
        with:
          name: cyclonedx-sbom
          path: _manifest/spdx_2.2/manifest.json