name: SBOM Generator

on:
  push:
    branches: [ master ] # Pas aan naar 'main' of je default branch indien nodig
  pull_request:
    branches: [ master ] # Pas aan naar 'main' of je default branch indien nodig
  workflow_dispatch:

permissions:
  contents: read
  actions: read
  security-events: write

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Generate SBOM
        uses: anchore/sbom-action@v0
        with:
          format: cyclonedx-json
          output-file: raw-sbom.json

      - name: Format JSON
        run: |
          jq . raw-sbom.json > sbom.json

      - name: Upload SBOM artifact
        uses: actions/upload-artifact@v4
        with:
          name: cyclonedx-sbom
          path: sbom.json